apiVersion: v1
kind: Service
metadata:
  name: goaccount-svc
  namespace: gons
  labels:
    app: goaccount
spec:
  type: NodePort
  selector:
    app: goaccount
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30000
      name: http

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: goaccount-pod
  namespace: gons
  labels:
    app: goaccount
spec:
  serviceName: goaccount-svc
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: goaccount
  template:
    metadata:
      labels:
        app: goaccount
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: goaccount
          image: local/goaccount:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: HOST
              value: ""
            - name: DB_HOST
              value: "postgres-svc"
            - name: DB_LOG
              value: "enable"
