apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: gons
data:
  POSTGRES_DB: account
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: secret

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config-init
  namespace: gons
data:
  init.sql: |
    CREATE USER kube WITH PASSWORD 'secret' CREATEDB;
    GRANT ALL PRIVILEGES ON DATABASE account TO kube;

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: gons
  labels:
    app: goaccount
spec:
  serviceName: postgres-srv
  selector:
    matchLabels:
      app: goaccount
  template:
    metadata:
      labels:
        app: goaccount
    spec:
      containers:
        - name: db
          image: postgres:14-alpine
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: db-config
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-init
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        -  name: db-init
           configMap:
             name: db-config-init
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: gons
  labels:
    app: goaccount
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      nodePort: 30432
  selector:
    app: goaccount
