apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data
  namespace: gons
  labels:
    app: goaccount
    type: local
spec:
  storageClassName: postgres-storage-class
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgresql"
  persistentVolumeReclaimPolicy: Retain

---
# Create a PersistentVolumeClaim to request a PersistentVolume storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-claim
  namespace: gons
  labels:
    app: goaccount
    type: local
spec:
  storageClassName: postgres-storage-class
  # the volume can be mounted as read-write by a single node.
  # ReadWriteOnce access mode still can allow multiple pods to access the volume when the pods are running on the same node.
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
