apiVersion: v1
kind: Service
metadata:
  name: goaccount-svc
  namespace: gons
  labels:
    app: goaccount
spec:
  type: NodePort
  selector:
    app: goaccount
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000
      name: http

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: goaccount-pod
  namespace: gons
  labels:
    app: goaccount
spec:
  serviceName: goaccount-svc
  replicas: 1
  minReadySeconds: 10
  selector:
    matchLabels:
      app: goaccount
  template:
    metadata:
      labels:
        app: goaccount
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: goaccount
          image: local/goaccount:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: HOST
              value: ""
            - name: PORT
              value: "80"
            - name: DB_HOST
              value: "postgres-svc"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "account"
            - name: DB_USERNAME
              value: "admin"
            - name: DB_PASSWORD
              value: "secret"
            - name: DB_TIMEZONE
              value: "UTC"
            - name: DB_SSL_MODE
              value: "disable"
            - name: DB_LOG_PATH
              value: "/var/log/go-account"
            - name: APP_JWT_URL
              value: "http://host.docker.internal:8080"
